// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message_manager/proto/request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 請求資料結構
type RequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // 改為 string 類型，更容易處理
	SourceService string                 `protobuf:"bytes,4,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	TargetService string                 `protobuf:"bytes,5,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	mi := &file_message_manager_proto_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_message_manager_proto_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_message_manager_proto_request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestData) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RequestData) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *RequestData) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

// 響應資料結構
type ResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_message_manager_proto_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_message_manager_proto_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_message_manager_proto_request_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseData) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ResponseData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ResponseData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 通用訊息結構
type MessageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SourceService string                 `protobuf:"bytes,3,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	TargetService string                 `protobuf:"bytes,4,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	mi := &file_message_manager_proto_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_message_manager_proto_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_message_manager_proto_request_proto_rawDescGZIP(), []int{2}
}

func (x *MessageData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MessageData) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MessageData) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *MessageData) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *MessageData) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_message_manager_proto_request_proto protoreflect.FileDescriptor

const file_message_manager_proto_request_proto_rawDesc = "" +
	"\n" +
	"#message_manager/proto/request.proto\x12\x0emessagemanager\"\xa9\x01\n" +
	"\vRequestData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12%\n" +
	"\x0esource_service\x18\x04 \x01(\tR\rsourceService\x12%\n" +
	"\x0etarget_service\x18\x05 \x01(\tR\rtargetService\"\x8c\x01\n" +
	"\fResponseData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xaf\x01\n" +
	"\vMessageData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12%\n" +
	"\x0esource_service\x18\x03 \x01(\tR\rsourceService\x12%\n" +
	"\x0etarget_service\x18\x04 \x01(\tR\rtargetService\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayloadB\x1eZ\x1cgodemo/message_manager/protob\x06proto3"

var (
	file_message_manager_proto_request_proto_rawDescOnce sync.Once
	file_message_manager_proto_request_proto_rawDescData []byte
)

func file_message_manager_proto_request_proto_rawDescGZIP() []byte {
	file_message_manager_proto_request_proto_rawDescOnce.Do(func() {
		file_message_manager_proto_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_manager_proto_request_proto_rawDesc), len(file_message_manager_proto_request_proto_rawDesc)))
	})
	return file_message_manager_proto_request_proto_rawDescData
}

var file_message_manager_proto_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_message_manager_proto_request_proto_goTypes = []any{
	(*RequestData)(nil),  // 0: messagemanager.RequestData
	(*ResponseData)(nil), // 1: messagemanager.ResponseData
	(*MessageData)(nil),  // 2: messagemanager.MessageData
}
var file_message_manager_proto_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_manager_proto_request_proto_init() }
func file_message_manager_proto_request_proto_init() {
	if File_message_manager_proto_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_manager_proto_request_proto_rawDesc), len(file_message_manager_proto_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_manager_proto_request_proto_goTypes,
		DependencyIndexes: file_message_manager_proto_request_proto_depIdxs,
		MessageInfos:      file_message_manager_proto_request_proto_msgTypes,
	}.Build()
	File_message_manager_proto_request_proto = out.File
	file_message_manager_proto_request_proto_goTypes = nil
	file_message_manager_proto_request_proto_depIdxs = nil
}
