FROM golang:1.24.1-alpine AS builder

WORKDIR /app

# 複製 go.mod 和 go.sum
COPY go.mod go.sum ./

# 下載依賴
RUN go mod download

# 複製源代碼
COPY create-topics.go .

# 編譯應用程序
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o topics create-topics.go

# 使用 alpine 作為運行時環境
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/topics .

CMD ["./topics"]