apiVersion: batch/v1
kind: Job
metadata:
  name: create-rocketmq-topics
  labels:
    app: create-topics
spec:
  template:
    metadata:
      labels:
        app: create-topics
    spec:
      containers:
      - name: create-topics
        image: harbor.trevi-dev.cc/cpp_run/rocketmq-topics:latest
        env:
        - name: ROCKETMQ_NAMESERVER
          value: "10.1.7.229:9876"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 3 