apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-server
  labels:
    app: rocketmq-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-server
  template:
    metadata:
      labels:
        app: rocketmq-server
    spec:
      containers:
      - name: rocketmq-server
        image: harbor.trevi-dev.cc/cpp_run/rocketmq-server:v4
        env:
        - name: ROCKETMQ_NAMESERVER
          valueFrom:
            configMapKeyRef:
              name: rocketmq-config
              key: nameserver
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-server-service
  labels:
    app: rocketmq-server
spec:
  selector:
    app: rocketmq-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP 